language: java
jdk:
  - openjdk8
addons:
  #srcclr: true
  postgresql: "9.3"
before_script:
  - psql -U postgres -c "create user test with password 'test';"
  - psql -c 'create database test owner test;' -U postgres
# Skip the default mvn command because we want to set the profile explicitly
before_install:
  - |
    if [ "$TRAVIS_EVENT_TYPE" != "cron" ]
    then
      export NOSCAN=1
    fi
install: true
script:
  #- mvn -Ppackagecloud -DskipTests -Dcheck1 verify
  #- mvn -Ppackagecloud -DskipTests -Dcheck2 clean verify
  #- mvn -Ppackagecloud -e clean package
  - psql -U test -l
  - psql -U test -d test -c '\dt'
  #- mvn clean package
  #- mvn test
  - mvn -e -Dpostgres.database.url=jdbc:postgresql://localhost/test -Dpostgres.database.user=test -Dpostgres.database.password=test -DskipTests -P postgres clean package
  - java -jar target/vertx-*-SNAPSHOT.jar
  - psql -U test -d test -c '\dt'
after_failure:
  - echo "\n=== SUREFIRE REPORTS ===\n"
  - for F in target/surefire-reports/*.txt; do echo $F; cat $F; echo; done
